50:
  /system/chassis/motherboard/fan0:
    xyz.openbmc_project.Inventory.Item:
      PrettyName:
        IPMIFruProperty: Product Name
        IPMIFruSection: Product
51:
  /system/chassis/motherboard/fan1:
    xyz.openbmc_project.Inventory.Item:
      PrettyName:
        IPMIFruProperty: Product Name
        IPMIFruSection: Product
52:
  /system/chassis/motherboard/fan2:
    xyz.openbmc_project.Inventory.Item:
      PrettyName:
        IPMIFruProperty: Product Name
        IPMIFruSection: Product
53:
  /system/chassis/motherboard/fan3:
    xyz.openbmc_project.Inventory.Item:
      PrettyName:
        IPMIFruProperty: Product Name
        IPMIFruSection: Product
54:
  /system/chassis/motherboard/fan4:
    xyz.openbmc_project.Inventory.Item:
      PrettyName:
        IPMIFruProperty: Product Name
        IPMIFruSection: Product
55:
  /system/chassis/motherboard/fan5:
    xyz.openbmc_project.Inventory.Item:
      PrettyName:
        IPMIFruProperty: Product Name
        IPMIFruSection: Product
